### ISSUE TITLE
Can't download OSX zip file from http://esp.mcmaster.ca/?page_id=1759

### ISSUE THREAD

**Issue by rbnpi** [d0kt0r0/EspGrid#1]
Links are not working to download http://esp.mcmaster.ca/EspGrid-builds/EspGrid-0.53.5-OSX.zip
or download http://esp.mcmaster.ca/EspGrid-builds/EspGrid-0.53.5-OSX.zip
from your page http://esp.mcmaster.ca/?page_id=1759

Please can you fix them.

**Comment by dktr0** [comment]
Yes, there’s a problem with the web server at 
esp.mcmaster.ca - it’s not just broken links or something like that. Thanks for noticing it. If you send me a real email, not through github’s notifications, and let me know which one you are interested in, I’ll send it to you in an email.

-David

On Nov 16, 2015, at 6:00 PM, Robin Newman notifications@github.com wrote:

Links are not working to download 
http://esp.mcmaster.ca/EspGrid-builds/EspGrid-0.53.5-OSX.zip
or download 
http://esp.mcmaster.ca/EspGrid-builds/EspGrid-0.53.5-OSX.zip
from your page http://esp.mcmaster.ca/?page_id=1759
Please can you fix them.
—
Reply to this email directly or 
view it on GitHub.
