### ISSUE TITLE
Can't launch after building on Linux

### ISSUE THREAD

**Issue by gilfuser** [d0kt0r0/EspGrid#3]
Hi there.
I'm very interested in using EspGrid, but I couldn't make it work.
I got a lot exeptions warnings while building and at the end `espgridd` was not recognised as a valid command to launch it.
I'm using Linux Ubuntu Studio 18.10
Here's the link for the messages I got while building: [gist](https://gist.github.com/gilfuser/dd9df14da56ed0b77edd627c468a315e)

Any help would be much appreciated.

bests,
Gil

**Comment by gilfuser** [comment]
Should I get a gui when launching it, so, I could start things properly?
I tried to use it even without it and got [these](https://gist.github.com/gilfuser/83ba3861513d216c17456042ef3509ed) messages.

**Comment by gilfuser** [comment]
> There's no GUI in Linux - just OS X. Everything you can do with the GUI you should be able to do through the SuperCollider quark, I think. I think you just need to do t.start in SuperCollider to unpause the tempo.

It worked! Thank you!
Here what I have in SC:
```
t = EspClock.new;
TempoClock.default = t;
t.start;
```

**Comment by dktr0** [comment]
Great! :)
