### ISSUE TITLE
[linux] can't make sense of the values returned by EspGrid

### ISSUE THREAD

**Issue by the-drunk-coder** [d0kt0r0/EspGrid#4]
I just started toying around with EspGrid (sending messages with liblo's oscsend and receiving them with oscdump), so maybe there's just a misunderstanding, but somehow I can't make a lot of sense of the values that espgridd returns.

Here's what I've observed so far:
* the number of beats stays on 0 
* the number of seconds never changes
* when switching the beat off (`/esp/beat/on 0`), the number jumps to some value and then stays there when I switch it on
* there's constant messages like this in the console:
```
2019-04-14 01:24:30.385 espgridd[28389:28391] autorelease called without pool for object (0x7f2d50145d50) of class GSCInlineString in thread <NSThread: 0x55f8e1b59ee0>{name = (null), num = 28391}
```
* when the beat is switched off, the frequency of the messages above increases rapidly

Am i missing something here? Do i have to un-pause the beat or take some other steps to get valid results ? I'm a bit lost ...

**Comment by dktr0** [comment]
That is exactly as it should be. The numbers describe a metric grid so they only change when the tempo is changed or when espgrid's estimate of a tempo set remotely changes. The "number of beats" is the number of beats that had passed at the time indicated by the other parameters. To determine where you are "now" (ie. the current beat) you take the difference in time between now and the time reported in espgrid's tempo message, and multiply by the tempo (which is in cycles per seconds).

**Comment by dktr0** [comment]
PS - the autorelease message seems to be annoying and harmless (and only occurs on GNUstep).
