### ISSUE TITLE
autorelease called without pool for object of classes

### ISSUE THREAD

**Issue by gilfuser** [d0kt0r0/EspGrid#5]
Hi.
First of all thank you for making EspGrid. I have used in the past to live code things both in SuperCollider and Tidal in perfect sync.

I have a whole Linux (Ubuntu Studio 19.04) install and tried to put my live-code system up again, but there is something wrong going on. I'm getting lots of messages saying something like this:
` 2019-10-20 13:17:55.230 espgridd[1838:1838] autorelease called without pool for object (0x5565df7bedd0) of class GSCInlineString in thread <NSThread: 0x5565df6d26c0>{name = (null), num = 1838}`
When I start espgridd the classes menttioned are
GSCInlineString
GSAutoreleasedMemory
GSAttrDictionary
GSAutoreleasedMemory
GSDictionaryKeyEnumerator
GSMutableDictionary
NSIntNumber
NSCalendarDate
NSDataMalloc

Later, trying to use it, e.g. in SC
```
	TempoClock.default = EspClock.new;
	TempoClock.default.start;
	TempoClock.tempo = 110/60;
```
I'll get only GSCInlineString
`2019-10-20 13:18:07.264 espgridd[1838:1840] autorelease called without pool for object (0x7f0ec8003a90) of class GSCInlineString in thread <NSThread: 0x5565df7e4900>{name = (null), num = 1840}`

Then, if in Tidal I do `espgrid tidal` and change tempo, it won't change the tempo in SC side.

The other info at starting time are:
```
2019-10-20 13:17:55.334 espgridd[1838:1838] 330502122061: version 0.58.7
2019-10-20 13:17:55.343 espgridd[1838:1838] 330511445934: system=1571588275343634000 monotonic=330511427711
2019-10-20 13:17:55.344 espgridd[1838:1838] 330511842309:  person=skmecs broadcast=255.255.255.255 clockMode=4 verbosity=1
2019-10-20 13:17:55.344 espgridd[1838:1838] 330512658387 EspOscSocket: bound to UDP port 5510
2019-10-20 13:17:55.345 espgridd[1838:1838] 330513358932 EspSocket: bound to UDP port 5509
```

Do you know what's going on? Maybe some missing library?

kind regards,
Gil

**Comment by dktr0** [comment]
In my experience, all of the autorelease-related error messages are annoying but don't seem to get in the way of things working properly. From your message, the most likely thing is a mismatch between the Tidal-Esp code and espgridd - Tidal has changed a lot in the last year, and while I have occasionally been able to spend some energy tracking those changes... not always. I think the first thing would be to spell out how/when you installed Tidal, and - if known - what Tidal version you have?

**Comment by gilfuser** [comment]
I'm using Tidal 1.4.3 with vim (vim-tidal) and I've installed it through cabal. I'm following the instructions here:
https://tidalcycles.org/index.php/EspGrid_tempo_sharing

I just tested it and I can change tidal's tempo from SC, but then if I try to change the tempo from Tidal it sounds like if was trying it but the old tempo take over. It's a little bit difficult to explain. I could upload a screen record to show you if you think would help.

I'm starting EspGrid from the terminal `espgridd`, then:

In SC I'm doing this:

```supercollider
t = EspClock.new;
TempoClock.default = t;
t.tempo = 140/60/4
```

and in Tidal:

```haskell
espgrid tidal

p 1 $ "bd*4" # cps 1.5

setcps 0.5
```

**Comment by dktr0** [comment]
Sorry for the delayed reply. I can confirm that things aren't working with the most recent Tidal. I'll be able to take a closer look later this week and will ping the Tidal chat on chat.lurk.org as well.

**Comment by yaxu** [comment]
(copied from the chat)
I think the only recent changes to Tidal's clock have been to make cps changes more accurate https://github.com/tidalcycles/Tidal/issues/501

 It's possible there's a bug in there, but nothing obvious.

**Comment by yaxu** [comment]
@gilfuser I think you have to use `cpsEsp` rather than `setcps`

I've just tried it and it works, a bit of a glitch when changing tempo, but they ran at the same tempo but out of phase.

**Comment by dktr0** [comment]
Think I need to add a debug option to "espgrid" in the Tidal code base to figure out what is going on then.

**Comment by dktr0** [comment]
@gilfuser curious to know if cpsEsp solves your issue (it wouldn't solve mine...)

**Comment by gilfuser** [comment]
Hi @dktr0 and @yaxu

Thank you both.

cpsEsp works for me!

**Comment by gilfuser** [comment]
@yaxu do you think we should put that information here:
https://tidalcycles.org/index.php/EspGrid_tempo_sharing

I could do it.

**Comment by dktr0** [comment]
That's great to hear @gilfuser - I think that would be great if you updated/augmented the wiki.

@yaxu with reference to your out of phase observation - might you describe the scenario in which you observe that a little more? For example, was it two Tidal processes on separate machines or some other scenario?

**Comment by yaxu** [comment]
@dktr0 It was between supercollider and tidal on the same laptop

**Comment by dktr0** [comment]
@yaxu depending on what you are doing in SuperCollider it's very easy to have different latency settings than what you are getting from the Tidal events. Changing the SuperCollider server latency to match the Tidal usually helps. s.latency = ...

**Comment by gilfuser** [comment]
I also had to adjust SC server latency to make them sync.

**Comment by yaxu** [comment]
Gotcha, thanks!

**Comment by yaxu** [comment]
I wonder if `setcps` used to work with espgrid?

**Comment by dktr0** [comment]
I don't think so, because it would have had to know that espgrid was being used to know to fire an OSC message off in that direction?

**Comment by dktr0** [comment]
Although... there might have been a period where setcps was effectively being redefined as the one that communicates with espgrid? It's all a blur...
